### ISSUE TITLE
Download twitch-platform-6.5.jar Falt

### ISSUE THREAD

**Issue by ghost** [Enaium/ml4g#1]
Could not find twitch-platform-6.5.jar (tv.twitch:twitch-platform:6.5).
Searched in the following locations:
    https://libraries.minecraft.net/tv/twitch/twitch-platform/6.5/twitch-platform-6.5.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

Minecraft 1.8.9

The twitch-platform-6.5.jar in 1.8.9.json

"name": "tv.twitch:twitch-platform:6.5",
      "downloads": {
        "classifiers": {
          "natives-osx": {
            "path": "tv/twitch/twitch-platform/6.5/twitch-platform-6.5-natives-osx.jar",
            "url": "https://libraries.minecraft.net/tv/twitch/twitch-platform/6.5/twitch-platform-6.5-natives-osx.jar",
            "sha1": "5f9d1ee26257b3a33f0ca06fed335ef462af659f",
            "size": 455359
          },
          "natives-windows-32": {
            "path": "tv/twitch/twitch-platform/6.5/twitch-platform-6.5-natives-windows-32.jar",
            "url": "https://libraries.minecraft.net/tv/twitch/twitch-platform/6.5/twitch-platform-6.5-natives-windows-32.jar",
            "sha1": "206c4ccaecdbcfd2a1631150c69a97bbc9c20c11",
            "size": 474225
          },
          "natives-windows-64": {
            "path": "tv/twitch/twitch-platform/6.5/twitch-platform-6.5-natives-windows-64.jar",
            "url": "https://libraries.minecraft.net/tv/twitch/twitch-platform/6.5/twitch-platform-6.5-natives-windows-64.jar",
            "sha1": "9fdd0fd5aed0817063dcf95b69349a171f447ebd",
            "size": 580098
          }
        }
      },

My english is bad :(

**Comment by Enaium** [comment]
好了
